### ISSUE TITLE
Does this actually work to improve performance?

### ISSUE THREAD

**Issue by aaronjensen** [onnimonni/docker-unison#2]
It doesn't seem like this helps performance at all, as mounted volumes appear to be mounted volumes (aka slow)

```
# time dd if=/dev/zero of=test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out
102400000 bytes (102 MB) copied, 29.7829 s, 3.4 MB/s

real    0m29.802s
user    0m0.260s
sys     0m2.640s
```

The actual container that is running unison is fast:

```
# time dd if=/dev/zero of=test.dat bs=1024 count=100000
100000+0 records in
100000+0 records out

real    0m0.267s
user    0m0.000s
sys     0m0.000s
```

But I can't figure out how to get that to translate over to any container that gets its `volumes_from`

**Comment by derimagia** [comment]
(Same guy from the other thread, didn't want to spam everyone in the list) - What are your folders that you are sharing in the docker gui? There's a new tab for it.

**Comment by aaronjensen** [comment]
```
/Users
/Volumes
/tmp
/private
```

**Comment by aaronjensen** [comment]
Ugh, nevermind me. Somehow the one container i was testing still had a shared volume mounted to the same place: .:/myapp. and it was winning out config wise. Once I got rid of that it was fast again. Sorry for the rabbit hole.
