### ISSUE TITLE
Dockerfile incorrect in ENTRYPOINT section

### ISSUE THREAD

**Issue by makshc2** [onnimonni/docker-unison#20]
In the end of Dockerfile there is syntax error
`ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]`
But it should be /sbin/**init**. Please move "t" symbol after "ini".

**Comment by onnimonni** [comment]
Please make a PR.

**Comment by scytacki** [comment]
@makshc2 the use of `tini` is intentional. You can read about it here: https://github.com/krallin/tini 
Are you having a problem with the image not working?

It was added in this PR:
https://github.com/onnimonni/docker-unison/pull/19
