### ISSUE TITLE
UNISON_VERSION not needed anymore

### ISSUE THREAD

**Issue by EugenMayer** [onnimonni/docker-unison#3]
The origin version from used UNISON_VERSION but it seems, just to swap version. You do no longer need it, AFAICS, so i can happily remove it from the env vars in docker-sync, right? Thanks!

**Comment by onnimonni** [comment]
Original version included multiple versions. I think that's bad practice and this container will have tags for every unison version release instead.

**Comment by EugenMayer** [comment]
Thats for sure not the docker-philospohy - it should have exactly one version per image. Thank you!

**Comment by onnimonni** [comment]
@EugenMayer I can contribute and help and maintain the image even if it's under the docker-sync project. I would advice for you to create a new organisation called **docker-sync** and you can add me as a contributor for the docker-unison repo, if this is something you want to have :).

**Comment by EugenMayer** [comment]
@onnimonni i would love you to contribute but i would leave the image itself as read only, both images, to ensure there stability. Since i do not have any branch-permission things, i would suggest using forks and pull requests?

thank you!
