### ISSUE TITLE
Choose the user unison is running

### ISSUE THREAD

**Issue by gagarine** [onnimonni/docker-unison#5]
Files created by unison on the container will be owned by the user unison is running. So it would be great to be able to chose a user name on witch unison run.

This is a needed feature to solve https://github.com/EugenMayer/docker-sync/issues/40

**Comment by onnimonni** [comment]
I think you would need to choose `UID` and `GID` instead of usernames because docker-unison container doesn't really know which users you have in other containers or host machine.

**Comment by gagarine** [comment]
Yes but unison is capable of matching username. (how I get it)

Both option can be interesting.

**Comment by onnimonni** [comment]
Alright I didn't know that. To spare some time can you point me in the section of unison which says this?

And if possible to provide the 2 commands needed in order to achieve this:
- local command to connect to remote server
- remote command for running unison server

**Comment by EugenMayer** [comment]
@onnimonni on rsync, we do 

https://github.com/EugenMayer/docker-rsyncd-image/blob/master/run#L10
https://github.com/EugenMayer/docker-rsyncd-image/blob/master/run#L13

using 

https://github.com/EugenMayer/docker-sync/blob/master/example/docker-sync.yml#L38
https://github.com/EugenMayer/docker-sync/blob/master/example/docker-sync.yml#L41

maybe that is an option for unison also? the rsyncd daemon does then map those files

https://github.com/EugenMayer/docker-rsyncd-image/blob/master/run#L20

**Comment by gagarine** [comment]
It's in the https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html . Sadly their is no anchor so I copied the relevant parts:

Those are the options:

> **numericids**
>     When this flag is set to true, groups and users are synchronized numerically, rather than by name.
> The special uid 0 and the special group 0 are never mapped via user/group names even if this preference is not set.
> 
> **group**
>     When this flag is set to true, the group attributes of the files are synchronized. Whether the group names or the group identifiers are synchronized depends on the preference numerids.
> 
> **owner**
>     When this flag is set to true, the owner attributes of the files are synchronized. Whether the owner names or the owner identifiers are synchronizeddepends on the preference numerids.

How it's works

> **Permissions**
> Synchronizing the permission bits of files is slightly tricky when two different filesytems are involved (e.g., when synchronizing a Windows client and a Unix server). In detail, here's how it works:
> 
>  When the permission bits of an existing file or directory are changed, the values of those bits that make sense on both operating systems will be propagated to the other replica. The other bits will not be changed.
> - When a newly created file is propagated to a remote replica, the permission bits that make sense in both operating systems are also propagated. The values of the other bits are set to default values (they are taken from the current umask, if the receiving host is a Unix system).
> - For security reasons, the Unix setuid and setgid bits are not propagated.
> - The Unix owner and group ids are not propagated. (What would this mean, in general?) All files are created with the owner and group of the server process

As you see their is no option to "force" a user. What I read is files are by default (so if owner and group are set to false) created with the user running unison.

**Comment by onnimonni** [comment]
Yes but I don't see why the username/group would matter at all? Just the uid/gid?

`-group` and `-owner` flags use whatever they get from system. So the only option which would matter is the `-numericids`

**Comment by gagarine** [comment]
Yes `-numericids` flag choose between matching the name or using uid/gid when you have `-group` or -`owner`set to true.

**Comment by onnimonni** [comment]
@EugenMayer @gagarine I'm happy to merge any PR. Unfortunately I don't have enough time for looking into this and it's not a priority in my use case.

**Comment by onnimonni** [comment]
This was closed in 19183214ad2bef73a4d7401eb6bf170bc1e2fdcb.
